apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncthing.fullname" . }}
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
      protocol: {{ .protocol }}
  {{- end }}
  selector:
    {{- include "syncthing.selectorLabels" . | nindent 4 }}
