apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mariadb.fullname" . }}-initdb
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
data:
  initdb.sql: |
{{ .Files.Get "files/initdb.sql" | indent 4 }}
