apiVersion: v1
kind: Service
metadata:
  name: {{ include "kopia.fullname" . }}
  labels:
    {{- include "kopia.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    # - port: {{ .Values.service.port }}
      # targetPort: http
    - port: 80
      targetPort: 51515
      protocol: TCP
      name: http
  selector:
    {{- include "kopia.selectorLabels" . | nindent 4 }}
