apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "copyparty.fullname" . }}-config
data:
  copyparty.conf: |
    [global]
      p: 8086, 3923       # Listen on ports 8086 and 3923
      z, qr               # Enable Zeroconf (LAN service discovery) and QR code login
      shr: /shr           # Shared folder path
      hist: /cfg/hists/   # History/log directory
      xff-src: lan
      rproxy: 1

    [accounts]
      jdansev: copyparty_password  # Create a user named jdansev with password

    [/]
      /data               # Expose /data as the root volume
      accs:
        rwdma: jdansev     # Give user 'jdansev' read/write/delete/admin permissions on this volume
