apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ntfy.fullname" . }}-config
data:
  server.yml: |
    base-url: {{ .Values.config.baseUrl }}
    upstream-base-url: {{ .Values.config.upstreamBaseUrl }}
